langchain-ai/langchain-google

- libs/vertexai/langchain_google_vertexai/functions_utils.py
- libs/vertexai/tests/unit_tests/test_function_utils.py
- Fixed Key Error 'required' when defining a tool with no arguments.
- Added unit test for function utils
> Fix no args function call

- libs/vertexai/langchain_google_vertexai/vision_models.py
- libs/vertexai/tests/integration_tests/test_vision_models.py
- libs/vertexai/tests/unit_tests/test_vision_models.py
Added support fort `imagetext` models
- `VertexAIImageCaptioning` LLM based implementation of image captioning
- `VertexAIImageCaptioningChat` Chat based implementation of image captioning
- `VertexAIVisualQnAChat` Chat based implementation of image question and answering
> Added support for imagetext models

- libs/vertexai/langchain_google_vertexai/_image_utils.py
- libs/vertexai/langchain_google_vertexai/vision_models.py
- libs/vertexai/tests/integration_tests/test_vision_models.py
- libs/vertexai/tests/unit_tests/test_image_utils.py
- libs/vertexai/tests/unit_tests/test_vision_models.py
Added classes:
- `VertexAIImageGenerationChat`
- `VertexAIImageEditorChat`
To `vision_models`
> VisionModels: Added ImageGeneration and ImageEdition

- libs/vertexai/.gitignore
- libs/vertexai/langchain_google_vertexai/embeddings.py
- libs/vertexai/tests/integration_tests/conftest.py
- libs/vertexai/tests/integration_tests/test_embeddings.py
- libs/vertexai/tests/integration_tests/test_vision_models.py
- libs/vertexai/tests/unit_tests/test_embeddings.py
Add support for multimodalembedding model as model type on VertexAIEmbeddings.
- Add embed_image method, only valid for multimodalembedding model.
- Make embed_documents and embed_query only available for text models.
- TODO: adapt embded_documents and embded_query to also work with multimodalembedding models.
> feat: add support for multimodal model and add embed_image

- libs/vertexai/tests/integration_tests/test_tools.py
As the tests/integration_tests/test_tools.py::test_multiple_tools is failing because of the missing GOOGLE_SEARCH_API_KEY we will temporary move it to extended so that it will be skipped
> Moved failing test to extended to be skipped

- libs/vertexai/langchain_google_vertexai/_base.py
- libs/vertexai/langchain_google_vertexai/llms.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
- libs/vertexai/tests/unit_tests/test_llm.py
Related to https://github.com/langchain-ai/langchain/discussions/18975
Didn't go the usual pydantic `Field(..., alias="model")` route because that would've caused mypy errors for anyone passing in `model_name` (ie for all existing code).
> vertexai[patch]: support `model` param

- libs/vertexai/langchain_google_vertexai/_image_utils.py
- Follow-up to https://github.com/langchain-ai/langchain-google/pull/108
- Shouldn't be needed after https://github.com/googleapis/python-storage/pull/1249 is merged/released
> fix: Add `blob.reload()` to populate `blob.content_type`

- libs/community/langchain_google_community/drive.py
**Description:** Add Google Drive document access identities to metadata
**Dependencies:** none
**Documentation:** GoogleDrive documentation update with `load_auth` usage to be updated with PR: https://github.com/langchain-ai/langchain/pull/18813
> [feat]: add authorization identities to GoogleDriveLoader.

- libs/vertexai/langchain_google_vertexai/vectorstores/__init__.py
- libs/vertexai/langchain_google_vertexai/vectorstores/document_storage.py
- libs/vertexai/langchain_google_vertexai/vectorstores/vectorstores.py
- libs/vertexai/tests/integration_tests/test_vectorstores.py
Implement `BaseStore` interface for document storage, both GCS and Datastore
- Change custom interface to conform to `mset` `mget`
- Implement `mdelete` and `yield_keys`
- Update tests
> [vectorstores] Implement BaseStore interface for document storage

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
```python
from langchain.agents import AgentExecutor, create_tool_calling_agent, tool
from langchain_google_vertexai import ChatVertexAI
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
prompt = ChatPromptTemplate.from_messages(
[
("human", "{input}"),
MessagesPlaceholder("agent_scratchpad"),
]
)
model = ChatVertexAI(model_name="gemini-pro", temperature=0)
@tool
def magic_function(input: int) -> str:
"""Applies a magic function to an input."""
return str(input + 2)
tools = [magic_function]
agent = create_tool_calling_agent(model, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
agent_executor.invoke({"input": "what is the value of magic_function(3)?"})
```
```
> Entering new AgentExecutor chain...
Invoking: `magic_function` …
```
> vertexai[patch]: enable agents for vertex

- libs/vertexai/langchain_google_vertexai/_base.py
Added to additonal parameters to `_VertexAICommon` that affect `vertexai.__init__`.
- `api_transport`
- `api_endpoint`
There are additional parameters but I think it doesn't make sense to include them, is better to initialize them per session in my opinion.
> Add aditional parameters to vertexai init

- libs/community/langchain_google_community/drive.py
Description: 
This PR will add 3 new fields to metadata of Documents loaded by GoogleDriveLoader.
A new argument, `load_extended_matadata` is also added to enable these fields. 
Documentation:
Will be added in followup PR (on lagchain repo).
> Add owner, source and size to GoogleDriveLoaders Document's metadata.

- libs/genai/langchain_google_genai/llms.py
HarmCategory.ARM_CATEGORY_UNSPECIFIED: HarmBlockThreshold.BLOCK_NONE
from safety_settings = { ... } as HarmCategory.ARM_CATEGORY_UNSPECIFIED no longer exists.
https://ai.google.dev/docs/safety_setting_gemini
I had a meeting discussing mental healthcare and I had the question: "What was discussed about cyberbullying?".
Once I removed "HarmCategory.ARM_CATEGORY_UNSPECIFIED: HarmBlockThreshold.BLOCK_NONE", my code worked
> Update llms.py : Removed HarmCategory.ARM_CATEGORY_UNSPECIFIED

- libs/vertexai/langchain_google_vertexai/_base.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/langchain_google_vertexai/embeddings.py
- libs/vertexai/langchain_google_vertexai/gemma.py
- libs/vertexai/langchain_google_vertexai/llms.py
- libs/vertexai/langchain_google_vertexai/model_garden.py
- libs/vertexai/pyproject.toml
- libs/vertexai/tests/integration_tests/test_embeddings.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
- libs/vertexai/tests/unit_tests/test_embeddings.py
- libs/vertexai/tests/unit_tests/test_llm.py
Related to https://github.com/langchain-ai/langchain/issues/20085
> vertexai[patch]: standardize model params

- libs/vertexai/langchain_google_vertexai/model_garden.py
The update allows a user to optionally use an access_token instead of default credentials when using the ChatAnthropicVertex class.
> Add support for access_token parameter

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
Fixes https://github.com/langchain-ai/langchain/issues/20738.
> Add media support to vertex chat_models

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/unit_tests/test_chat_models.py
This change fixes the issue with running `ChatGoogleGenerativeAI` inside a `ThreadPoolExecutor` and requires initializing the model inside an event loop to enable async client
> require that async client be initialized inside a running event loop

- libs/community/langchain_google_community/vertex_ai_search.py
This commit updates the VertexAISearchRetriever configuration to forbid unknown fields during initialization. This change ensures that users receive immediate feedback if they accidentally pass a wrong or misspelled attribute name, improving error handling and robustness of the initialization process.
The change modifies the Pydantic BaseModel configuration to set `extra = Extra.forbid`, which throws errors for any extraneous fields. This update is essential for preventing runtime errors related to attribute misconfigurations and is in line with best practices for Pydantic model setup.
> community: enforce attribute validation in VertexAISearchRetriever

- libs/genai/langchain_google_genai/embeddings.py
- libs/genai/tests/integration_tests/test_embeddings.py
fixes https://github.com/langchain-ai/langchain-google/issues/247
> fix return type for GoogleGenerativeAIEmbeddings

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/poetry.lock
- libs/genai/pyproject.toml
- libs/genai/tests/integration_tests/test_chat_models.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/poetry.lock
- libs/vertexai/pyproject.toml
- libs/vertexai/tests/integration_tests/test_chat_models.py
langchain-core 0.2.2 released a standard field to store usage metadata returned from chat model responses, such as input / output token counts. AIMessage objects have a `.usage_metadata` attribute which can hold a [UsageMetadata](https://api.python.langchain.com/en/latest/messages/langchain_core.messages.ai.UsageMetadata.html) dict. For now it is only holding token counts. Standardizing this information makes it simpler to track in monitoring / observability platforms and similar applications.
Here we unpack usage metadata returned by GenAI and Vertex gemini and non-gemini models onto AIMessages generated by chat models.
> vertexai, genai: add support for UsageMetadata

- libs/vertexai/langchain_google_vertexai/embeddings.py
- libs/vertexai/tests/unit_tests/test_embeddings.py
How to reproduce the error:
```
embedding_model = VertexAIEmbeddings(
model_name="text-embedding-004",
project=PROJECT_ID
)
queries = [f"random query{i}" for i in range(500)]
query_embeddings = embedding_model.embed(queries)
assert len(query_embeddings) == len(queries)
```
> Fixes embeddings duplication in first call

- libs/vertexai/tests/integration_tests/test_chat_models.py
Test has failed last two days with:
> google.api_core.exceptions.InvalidArgument: 400 Please ensure that function response turn comes immediately after a function call turn. And the number of function response parts should be equal to number of function call parts of the function call turn.
There should be one ToolMessage per tool call.
> vertex: fix test

- libs/genai/langchain_google_genai/_function_utils.py
- libs/genai/langchain_google_genai/chat_models.py
Fix #234.
I'm not sure the root cause.
_function_utils.py is refactored with investigating.
Sorry, I didn't care vertexai side because no environment with me.
```
(gamebook) jinno@jinno-desktop:~/git/drill/gamebook/codeinterpreter_api_agent$ python ../test/test_shell_tool.py 
・・・
File "/home/jinno/.local/share/virtualenvs/gamebook-7W9hF6PY/lib/python3.10/site-packages/langchain_google_genai/_function_utils.py", line 139, in <dictcomp>
"type_": TYPE_ENUM[v["type"]],
KeyError: 'type'
```
```
(gamebook) jinno@jinno-desktop:~/git/drill/gamebook/codeinterpreter_api_agent$ python ../test/test_shell_tool.py 
_convert_pydantic_to_genai_function schema= {'title': 'ShellInput', 'description': 'Commands for the Bash Shell tool.', 'type': 'object', 'properties': {'commands': {'title': 'Commands', …
```
> fix: convert_to_genai_function_declarations

- libs/vertexai/langchain_google_vertexai/_anthropic_utils.py
Allow `ChatVertexAI` to get `stop_reason` in the `AIMessage` of the `stream`, `astream` result.
The reason for this change is that the `stop_reason` is also used in streaming to determine the next action.
```python
ai_message_chunk: AIMessageChunk = None
for chunk in model.stream([HumanMessage(content="Hello, world!")]):
ai_message_chunk = ai_message_chunk + chunk if ai_message_chunk else chunk
print(ai_message_chunk.response_metadata["stop_reason"], ai_message.response_metadata["stop_sequence"])
```
> chore: add stop_reason in ChatAnthropicVertex stream response

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/langchain_google_vertexai/functions_utils.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
The behavior of `ChatVertexAI.with_structured_output` when specifying a `dict` was different from `ChatOpenAI` and `ChatAnthropicVertex`, so it has been corrected.
- Modified to accept not only the `["name", "description", "parameters"]` format for the `dict` but also `["title", "description", "properties"]`.
- When a `dict` is specified as the schema, it now extracts properties from the output.
This is considered breaking as it changes existing functionality.
If this change is unacceptable, please feel free to close it.
> [Breaking] change the behavior of ChatVertexAI.with_structured_output when specifying a dict

- libs/vertexai/langchain_google_vertexai/_base.py
- Pulls the `api_transport` parameter from the default initializer if not provided
> [ChatVertexAI] Get `api_transport` from  initializer when not provided

- libs/vertexai/langchain_google_vertexai/embeddings.py
The endpoint sometimes returns 500 error but when retrying the call it works
> Add InternalServerError to retry_errors in VertexAIEmbeddings

- libs/community/langchain_google_community/gmail/utils.py
Add Domain-Wide Service Authentication and Authorization
This pull request introduces the ability to use domain-wide delegation for authentication and authorization in addition to the existing InstalledAppFlow method. The following changes have been made:
1. **Enhanced the `get_gmail_credentials` function:**
- Added support for domain-wide delegation using service account credentials.
- Introduced new parameters: `use_domain_wide` to switch between authentication methods and `delegated_user` to specify the user to impersonate.
2. **Updated `build_resource_service` function:**
- Included new parameters `use_domain_wide` and `delegated_user` to support domain-wide delegation.
- Ensured compatibility with both domain-wide delegation and InstalledAppFlow methods.
- Modified …
> Add domain-wide service authentification and authorization

- libs/community/langchain_google_community/gmail/create_draft.py
- libs/community/langchain_google_community/gmail/send_message.py
- libs/community/langchain_google_community/places_api.py
- libs/community/langchain_google_community/search.py
- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/langchain_google_genai/embeddings.py
- libs/genai/langchain_google_genai/llms.py
- libs/vertexai/langchain_google_vertexai/_base.py
- libs/vertexai/tests/integration_tests/test_chains.py
[Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) is flagging initialization of some [Pydantic](https://docs.pydantic.dev/latest/) objects (ie. objects of classes extending [`BaseModel`](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel)) as having missing arguments when optional arguments are not provided. Although the code still runs as it should, this type of error is a potential source of frustration for VS Code users.
For example, according to the doc string for the [`GoogleGenerativeAIEmbeddings`](https://api.python.langchain.com/en/latest/embeddings/langchain_google_genai.embeddings.GoogleGenerativeAIEmbeddings.html) class, it can be used in the following way:
```python
from langchain_google_genai import …
```
> Fix optional fields in Pydantic models

- libs/community/langchain_google_community/bq_storage_vectorstores/bigquery.py
> Fix: BigQueryVectorStore crashes on BQ tables with more than 5000 rows

- libs/genai/tests/integration_tests/test_chat_models.py
Integration tests failing with:
> google.api_core.exceptions.NotFound: 404 Gemini 1.0 Pro Vision has been deprecated on July 12, 2024. Consider switching to different model, for example gemini-1.5-flash.
> genai[patch]: update vision model used in integration tests

- libs/community/langchain_google_community/vertex_ai_search.py
Today, VertexAISearchRetriever allows to pass as arguments:
- get_extractive_answers=True => to get answers
- get_extractive_answers=False => to get segments
In the current behaviour, when get_extractive_answers=True (get answers), page numbers are appended at the end of the source field.
However, this is not the case for get_extractive_answers=False (get segments), although the field is present in the Vertex AI Search API answer.
This small change allows to also get the page number, when segments (get_extractive_answers=False) is used
> Support page number for segments

- libs/community/langchain_google_community/vertex_ai_search.py
Issue:
The doc_metadata dictionary is mutable, and its reference is reused across iterations. This means any modifications to doc_metadata during one iteration affect the metadata of all previously appended documents in the documents list. Since doc_metadata is modified in place (changing the "source" field), all documents in the documents list end up sharing the same metadata object. Thus, when the "source" is updated with a new pageNumber, it retroactively alters the metadata for all documents, causing unexpected and incorrect metadata values. Therefore, instead of each document having its own metadata with the correct pageNumber, all documents have their "source" pointing to the latest pageNumber processed in the loop.
Fix:
The changes are made by referring to …
> fix: wrong page number in document metadata

- libs/community/langchain_google_community/bq_storage_vectorstores/featurestore.py
Currently if a value stored in the document metadata is null, parsing the search results will throw a StopIteration Error.
The reason is that the feature.value is actually empty.
Changing the code as proposed will handle this case without errors.
> Update the FS logic to manage null values parsing

- libs/vertexai/langchain_google_vertexai/vision_models.py
- libs/vertexai/tests/integration_tests/test_vision_models.py
Add support for chains with text content in `VertexAIImageGeneratorChat`
Related to issue #382
> Support chaining in vision models

- libs/vertexai/langchain_google_vertexai/_utils.py
https://github.com/langchain-ai/langchain-google/issues/351
Note that `langchain_google_genai.chat_models` does not add the field if 'finish_reason' is empty.
https://github.com/langchain-ai/langchain-google/blob/c92d2b95145091aa0ee69d3db63ff882d7be8e45/libs/genai/langchain_google_genai/chat_models.py#L552-L553
However, I added the field as `None` to be consistent with 'citation_metadata'
https://github.com/langchain-ai/langchain-google/blob/c92d2b95145091aa0ee69d3db63ff882d7be8e45/libs/vertexai/langchain_google_vertexai/_utils.py#L175-L179
Let me know if you would like me to change it to match with `langchain_google_genai`
> add finish_reason to gemini gen info

- libs/vertexai/langchain_google_vertexai/_base.py
in current implementation there is :
```python
vertexai.init(
project=values.get("project"),
location=values.get("location"),
credentials=values.get("credentials"),
api_transport=values.get("api_transport"),
api_endpoint=values.get("api_endpoint"),
request_metadata=values.get("request_metadata"),
)
```
but `request_metadata` is ignored by pydantic as an extra and `default_metadata` is proper field that is storing additional headers
> Fix support for additional headers

- libs/vertexai/langchain_google_vertexai/chat_models.py
Bind tools in openai format so that they can be better traced (protobufs aren't well handled by most tracers, and gemini 
tool format doesn't match most other models).
> vertexai[patch]: bind tools in oai format

- libs/genai/Makefile
Changed command ruff -> ruff check.
This change avoid this error.
```
poetry run ruff .
error: `ruff <path>` has been removed. Use `ruff check <path>` instead.
```
https://github.com/astral-sh/ruff/tree/v0.4.10?tab=readme-ov-file#usage
> genai: fix Makefile about ruff check

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
Fixes https://github.com/langchain-ai/langchain-google/issues/383
[AIMessage.usage_metadata](https://api.python.langchain.com/en/latest/messages/langchain_core.messages.ai.AIMessage.html#langchain_core.messages.ai.AIMessage.usage_metadata) is a dedicated field for housing token counts. It supports [merging](https://github.com/langchain-ai/langchain/blob/3ab09d87d614686fb0341e47670d0bd611fb3449/libs/core/langchain_core/messages/ai.py#L349-L363) across message chunks.
Here we remove token counts from `generation_info`. In many cases, the token counts are zero for every chunk but the final chunk. So there was a work-around where token counts with value zero were removed (see `# remove 0 so that chunks can be merged` comment).
In some cases this doesn't hold-- specifically, streaming for …
> vertex[patch]: fix streaming for gemini-1.5-pro + vision

- libs/community/langchain_google_community/drive.py
the drive.readonly scope gives very broad access to an application and is therefore a restricted scope. Restricted scopes are a pain because it means the application using it needs to go through a google restricted scope security review (see: https://developers.google.com/identity/protocols/oauth2/production-readiness/restricted-scope-verification).
With this change, the scope gets reduced to a recommended scope (see: https://developers.google.com/drive/api/guides/api-specific-auth)
> Update drive.py to only use drive.file scope

- libs/vertexai/langchain_google_vertexai/_base.py
Currently, models in the `GEMINI` family have no default parameters set, whereas they are set for all other Google models. This implies models in the new `GEMINI_ADVANCED` family also have default parameters set, such `max_output_tokens=128` (which are meant for PaLM and Bison models). 
This PR aims to fix that by making the default parameter behavior of `GEMINI` and `GEMINI_ADVANCED` model families identical for now. We can update defaults for each model family in the future.
> fix: Standardize default parameters across Gemini and Gemini Advanced models

- libs/genai/Makefile
add mkdir -p option for make lint
🧹 Refactoring
- before
```
mkdir .mypy_cache; poetry run mypy . --cache-dir .mypy_cache
mkdir: ディレクトリ `.mypy_cache' を作成できません: ファイルが存在します
```
- after
```
mkdir .mypy_cache; poetry run mypy . --cache-dir .mypy_cache
```
> genai: add mkdir -p option for make lint

- libs/genai/tests/integration_tests/test_standard.py
- libs/genai/tests/unit_tests/test_standard.py
TODO:
- Add quota so we can test vision models;
- Fix xfails on structured output (currently doesn't appear to support JSON-schema inputs)
Will plan to merge as-is to support testing for pydantic v2 migration.
> genai[patch]: add standard tests

- libs/genai/tests/integration_tests/test_chat_models.py
- libs/genai/tests/integration_tests/test_standard.py
- libs/genai/tests/unit_tests/test_chat_models.py
- libs/genai/tests/unit_tests/test_standard.py
Existing tests do not run because they don't start with a `Test` prefix. Here we separate them into their own modules and get them in a running state.
> genai[patch]: fix standard tests

- libs/vertexai/langchain_google_vertexai/functions_utils.py
- libs/vertexai/tests/unit_tests/test_function_utils.py
`_format_json_schema_to_gapic` translates json schema to gapic. It appears tailored to json schema as generated from Pydantic V1 BaseModels. Here we update this function to accommodate Pydantic V2 models. We keep the original function as `_format_json_schema_to_gapic_v1` and route V1 BaseModels through it.
In Pydantic V1, an `Optional[int]` will be represented as an `integer` type that is not included in `required` fields. In Pydantic V2, it is represented as a union type (e.g., `{'anyOf': [{'type': 'integer'}, {'type': 'null'}], 'title': 'field_name'}` and included in `required` fields. Example:
```python
from typing import Optional
from pydantic.v1 import BaseModel as BaseModelV1
class PersonV1(BaseModelV1):
name: str
age: Optional[int]
PersonV1.schema()
```
```
{'title': 'PersonV1', …
```
> vertex: fix gapic conversion

- libs/vertexai/langchain_google_vertexai/functions_utils.py
- libs/vertexai/poetry.lock
- libs/vertexai/tests/unit_tests/test_function_utils.py
🆕 New Feature
🐛 Bug Fix
🧹 Refactoring
✅ Test
> catch pydantic v2 schemas in dict

- libs/vertexai/langchain_google_vertexai/chat_models.py
`ChatVertex.with_structured_output` has a bug in the case of:
- async
- schema passed as dict
Example:
```python
from langchain_google_vertexai import ChatVertexAI
model = ChatVertexAI(model_name="gemini-pro").with_structured_output(
schema={
"type": "object",
"title": "Grade",
"required": ["score"],
"properties": {
"score": {"type": "integer", "description": "Provide the score:"}
},
"description": "Grade the quiz based upon the above criteria with a score.",
}
)
await model.ainvoke("Mostly correct, 7.")
```
raises `NotImplementedError: RunnableGenerator(_yield_args) only supports sync methods.`.
Adding a standard test for this in monorepo.
> vertex[patch]: update parser in with_structured_output

- libs/genai/tests/integration_tests/test_chat_models.py
- libs/genai/tests/integration_tests/test_standard.py
In my local, these errors was shown.
```
FAILED tests/integration_tests/test_standard.py::TestGeminiAIStandard::test_stop_sequence - google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
```
```
FAILED tests/integration_tests/test_chat_models.py::test_chat_google_genai_function_calling_with_structured_output[models/gemini-1.5-pro-001] - google.api_core.exceptions.ResourceExhausted: 429 Resource has been exhausted (e.g. check quota).
```
https://github.com/langchain-ai/langchain-google/pull/465
✅ Test
> genai: fix integration_test to avoid 429 Resource has been exhausted

- libs/community/langchain_google_community/gmail/search.py
The gmail search tool would always return an empty list when searching for threads. This was due to the search resource being `messages()` even if `resource == Resource.THREADS`
Simple fix that searches based on resource.
🐛 Bug Fix
- Retrieve results based on resource before calling parse methods
- Call an instance of the GmailSearch tool with `resource=Resource.THREADS`
- Retrieved threads instead of empty list
> community: Fix gmail search for threads

- libs/genai/Makefile
I was always forget the test command.
```
$ make 
Makefile:59: 警告: ターゲット 'check_imports' のためのレシピを置き換えます
Makefile:15: 警告: ターゲット 'check_imports' のための古いレシピは無視されます
----
check_imports                - check imports
format                       - run code formatters
lint                         - run linters
test                         - run unit tests
tests                        - run unit tests
integration_test             - run integration tests(NOTE: "export GOOGLE_API_KEY=..." is needed.)  <= new
test TEST_FILE=<test_file>   - run all tests in file
```
I think integration_test will be fixed by.
https://github.com/langchain-ai/langchain-google/pull/465
But this PR passed. It looks rundomly.
> genai: add integration_test help message for Makefile

- libs/vertexai/langchain_google_vertexai/_base.py
Before this PR, subclasses of `_VertexAIBase` could have problems setting a default value (or `default_factory`) for the `project` attribute. For example,
```python
import pydantic as pd
from langchain_core.utils import from_env
from langchain_google_vertexai.chat_models import ChatVertexAI
class MyVertexChat(ChatVertexAI):
project: pd.Field(default_factory=from_env("MY_GOOGLE_PROJ"))
```
```
>>> MyVertexChat()
...
GoogleAuthError: Unable to find your project. Please provide a project ID by: ...
```
This is because not passing a `project` to the constructor means that `values["project"]` is unset in the `before` model validator, triggering the project lookup in the global config (which can fail).
https://github.com/langchain-ai/langchain-google/blob/af2ef994ee5429bce18899b2c0c327470eba7032 …
> vertexai: postpone `_VertexAIBase.project` validation

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
fixes https://github.com/langchain-ai/langchain-academy/issues/28#issuecomment-2369795773
> fixed sequential human messages with tool calling

- libs/community/langchain_google_community/vertex_ai_search.py
- libs/community/tests/unit_tests/test_vertex_ai_search.py
This PR introduces two new optional fields, `order_by` and `canonical_filter`, to the `VertexAISearchRetriever` class. These fields enhance the flexibility and control over search queries when using Google Vertex AI Search.
🆕 New Feature
✅ Test
https://github.com/langchain-ai/langchain-google/issues/530
I added the corresponding unit test for creating a search request to verify that the VertexAISearchRetriever correctly creates a `SearchRequest` object with the expected auto-populated fields, including the newly added `order_by` and `canonical_filter` fields.
Also, I tested it using my data in GCP, checking different configurations and verifying that the parameters are correctly applied and produce the expected results.
```
vertex = VertexAISearchRetriever(
project_id=project_id, …
```
> community: Add support for order_by and canonical_filter fields in VertexAISearchRetriever

- libs/vertexai/langchain_google_vertexai/_base.py
- libs/vertexai/tests/unit_tests/__snapshots__/test_standard.ambr
there's already project, location and model. no need for full_model_name to be serialized
> vertexai[patch]: exclude full_model_name from ser

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
Add the possibility of using text/enum as mimetype for controlled generation
Fixes #521
🆕 New Feature
> vertexai: Add enum response schema for controlled generation

- libs/vertexai/langchain_google_vertexai/_utils.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
Following up on https://github.com/langchain-ai/langchain-google/pull/534/files
Fixes behaviour when using astream_events and stream methods, which requires merging together metadata where some of the chunks might contain "nan" Float values.
e.g
```
left = {'avg_logprobs': 0.0, 'safety_ratings': []}
others = {'avg_logprobs': nan, 'safety_ratings': []}
```
E                   TypeError: Additional kwargs key avg_logprobs already exists in left dict and value has unsupported type <class 'float'>.
We introduce a generic integration test with langraph to catch this kind of errors in the future for any metadata field.
> vertexai: fix avg log probs nan values

- libs/community/langchain_google_community/bq_storage_vectorstores/bigquery.py
BigQueryVectorStore's `_create_filters` are post-filters. Now that BigQuery Vector Search supports pre-filtering on stored columns (https://cloud.google.com/bigquery/docs/vector-index#stored-columns), we can change all post-filters to pre-filters.
Note that this requires storing the columns that are referenced by the pre-filter. This cannot be done in Langchain yet (have to use the BQ CLI/UI directly). If the required columns are not stored, then the pre-filters will act as post-filters.
🆕 New Feature
Change the vector search query from:
```sql
SELECT *
FROM VECTOR_SEARCH(
Table <table>,
...)
WHERE <filter>
```
to 
```sql
SELECT *
FROM VECTOR_SEARCH(
(SELECT * FROM <table> WHERE <filter>),
...)
```
Run unit and integration tests.
> community: Change post-filters to pre-filters in BigQueryVectorStore

- libs/vertexai/langchain_google_vertexai/_utils.py
Fixes an issue where the Google VertexAI API integration was not correctly returning average log probabilities due to a condition that they be greater than zero. This PR ensures that the average log probabilities are returned by setting the condition that they be less than zero.
Co-authored-by: @jaymon0703
vertexai: fix avg log probs nan values #550
🐛 Bug Fix
- Modified the check that average log probabilities are greater than zero to be less than zero.
Tested locally by running `make test` for the vertexai package, and all tests passed successfully.
> vertexai: Fix returning average log probabilities

- libs/community/langchain_google_community/bq_storage_vectorstores/bigquery.py
- libs/community/langchain_google_community/vertex_ai_search.py
- libs/community/tests/unit_tests/test_vertex_ai_search.py
Add the option to bring your own embedding to the langchain retriever.
To use it you need to bring the model, the column of the datastore with the embedding and the ratio for the ranking_expression.
🆕 New Feature
✅ Test
> community: add custom embedding functionality to VertexAISearchRetriever

- libs/vertexai/langchain_google_vertexai/vectorstores/document_storage.py
- libs/vertexai/langchain_google_vertexai/vectorstores/vectorstores.py
As the `self._text_property_name` and other fields might contain large text, this fix prevents from indexing such fields that currently triggers an error (see Datastores's maximum size of an indexed string property [limitation](https://cloud.google.com/datastore/docs/concepts/limits)). This also saves datastore's costs, preventing a non necessary field to be indexed. We can now pass a list `exclude_from_indexes` to the class, which is the same list that the sdk expects in input when creating an entity.
🐛 Bug Fix
> [vertexai] Fix Datastore error on indexing large fields

- libs/genai/langchain_google_genai/_function_utils.py
While doing simple llm.invoke(...) call, with model that has binded tools via .bind_tools then it starts to print all tools info while invoking. The problem is in _function_utils.py file in _format_dict_to_function_declaration, which has forgotten (i believe) print statement which fires everytime on the function start.
> genai: Removed forgotten "print" statement in _function_utils.py

- libs/vertexai/langchain_google_vertexai/vectorstores/_searcher.py
- libs/vertexai/langchain_google_vertexai/vectorstores/vectorstores.py
This PR is very similar to #331, but fully implemented and with metadata filtering support.
Now, you can delete documents from VectorVertexAiSearch with:
```python
ids = [] # in case you know the datapoints id's you can add them here!
vector_store.delete(ids)
```
The more powerful feature is the ability to delete datapoints based on metadata. For example, to delete all datapoints originating from a specific source file:
```python
file_to_delete = "testing.pdf"
vector_store.delete(metadata={"source": file_to_delete})
```
You can filter by any metadata key-value pair, not just the source file. For instance, to delete all the documents 15th page:
```python
vector_store.delete(metadata={"page": 15}) 
```
> vectorstores: add vertex vector search datapoints deletion

- libs/vertexai/langchain_google_vertexai/_utils.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
Issue #570 mentions a unified logprobs interface that could improve upon the default formatting returned from Google. Inspired by OpenAI's formatting found [here](https://python.langchain.com/docs/how_to/logprobs/), this format was created for the `logprobs_result` from Google VertexAI.
Adds to - vertexai[patch]: Add logprobs support #570
🧹 Refactoring
```ruby
llm = ChatVertexAI(model="gemini-1.5-flash-001", logprobs=True) 
ai_msg = llm.invoke(messages)
ai_msg.response_metadata["logprobs_result"]
```
```
[
{'token': 'J', 'logprob': -1.549651415189146e-06, 'top_logprobs': []},
{'token': "'", 'logprob': -1.549651415189146e-06, 'top_logprobs': []},
{'token': 'adore', 'logprob': 0.0, 'top_logprobs': []},
{'token': ' programmer', 'logprob': -1.1922384146600962e-07, 'top_logprobs': []}, …
```
> vertexai[refactor]: Enhance logprobs

- libs/vertexai/langchain_google_vertexai/_anthropic_parsers.py
- libs/vertexai/langchain_google_vertexai/model_garden.py
- libs/vertexai/poetry.lock
- libs/vertexai/pyproject.toml
- libs/vertexai/tests/integration_tests/test_model_garden.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
This PR improves content processing in the Anthropic formatter to handle content blocks more elegantly, while also fixing a bug we noticed from switching from Langchain+Anthropic to Langchain+Anthropic-on-Vertex: 
{'type': 'invalid_request_error', 'message': 'messages.16: `tool_result` block(s) provided when previous message does not contain any `tool_use` blocks'}
We noticed this in this Merge Request: https://gitlab.com/gitlab-org/duo-workflow/duo-workflow-service/-/merge_requests/59. We worked around this by patching ChatAnthropicVertex._format_output, with the way [ChatAnthropic._format_output](https://github.com/langchain-ai/langchain/blob/e317d457cfe8586e4006b5f41e2c4f1e18a4d58c/libs/partners/anthropic/langchain_anthropic/chat_models.py#L753) is implemented in the main langchain …
> vertexai: refactor: simplify content processing in anthropic formatter

- libs/community/langchain_google_community/drive.py
issue: https://github.com/langchain-ai/langchain-google/issues/168
- Where "package" is genai, vertexai, or community
- Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes
- Example: "community: add foobar LLM"
Adds 'bring your own credentials' to the drive loader to allow more flexibility in deployments (cloud run service accounts, command line, jupyter notebooks, colab, etc).
- Allows for declaration of credentials created elsewhere (outside this module) to be used
- Relevant issues [(Port randomness)](issue: https://github.com/langchain-ai/langchain-google/issues/168)
- Any dependencies required for this change: None
Adds 'bring your own credentials' to the drive loader to allow more flexibility in deployments (cloud run service …
> Update GoogleDriveLoader to allow bring your own credentials

- libs/genai/langchain_google_genai/_image_utils.py
- libs/genai/poetry.lock
- libs/genai/pyproject.toml
- libs/genai/tests/integration_tests/test_chat_models.py
This pull request enhances the process of guessing MIME types by introducing an alternative method to determine the MIME type from file bytes when guessing from the filename fails. Additionally, it includes an integration test for a specific case related to remote URL images without file extensions.
- Updated `pyproject.toml` to add new dependency: `filetype`.
- Implemented MIME type guessing using the `filetype` library to analyze image bytes as a fallback mechanism.
- Added a new integration test for a remote URL image without a file extension (`https://picsum.photos/seed/picsum/200/300`). This URL is currently used in the example section of the README, but it does not work as intended.
🆕 New Feature
✅ Test
> genai[feat]: add filetype detection for images from bytes

- libs/vertexai/langchain_google_vertexai/_anthropic_utils.py
- libs/vertexai/langchain_google_vertexai/_image_utils.py
- libs/vertexai/langchain_google_vertexai/model_garden.py
Fixes #594
Till now very time the load_bytes was called a new gcs client was created. Now just one client is created. First i wanted to create the client in the constructor but I saw in the code that not always a client is created and in some environments it could have failed. So i want to be on the safe side and don't change the current behavior.
I don't know which tests i can add as i don't change any visible behavior. So tests should pass without problems.
> [vertexai]: Use one gcs client in Imageutils 

- libs/community/langchain_google_community/drive.py
Current version ignores google presentations/slides. 
Slides also support exporting the text via the same mechanism used here for regular docs. This PR adds slides/presentations to the type of docs that are searched and loaded for use in embeddings.
🆕 New Feature
> Community GoogleDriveLoader: Update drive.py to also parse google slides

- libs/community/langchain_google_community/bq_storage_vectorstores/featurestore.py
Allow similarity_search_by_vector() to return the entity_id as part of the metadata that is returned. 
Currently similarity_search_by_vector() returns slightly different information when looking at a BQ store versus a Feature Store. When executed against a BQ store the nearest neighbor entity ID is returned, but when executed against the Feature Store no entity ID is returned. To bring both into alignment we should include the entity_id for the Online Feature Store as well.
🆕 New Feature
🐛 Bug Fix
> Update _parse_proto_output function to include the entity_id as part of the metadata returned

- libs/genai/langchain_google_genai/_function_utils.py
- libs/genai/tests/unit_tests/test_function_utils.py
While working with [gregpr07/browser-use](https://github.com/gregpr07/browser-use), @mahlertom and I found several bugs in langchain handling of nested `Pydantic` structured in `with_structured_output`. Specifically, the issues occurred in `_get_properties_from_schema` method in `libs\genai\langchain_google_genai\_function_utils.py`.
1. The current implementation did not recursively handle cases of nested `glm.Type.OBJECT` and only took care of the first layer.
2. In cases where `pydantic` fields are required (no default value is provided), the method did not properly add these fields to the `required` list.
3. In cases where an object of type `glm.Type.OBJECT` had empty properties, there was an error that properties of type `glm.Type.OBJECT` must not be empty.
Fixes …
> genai: Fixed nested pydantic structures recursion

- libs/community/langchain_google_community/drive.py
- libs/community/tests/unit_tests/test_drive.py
This PR makes the Google Drive API scopes configurable in the GoogleDriveLoader class instead of using a hardcoded global constant. This change allows users to specify different scopes based on their needs while maintaining backward compatibility with the default `drive.file` scope.
Currently, the scope is hardcoded to `drive.file` which is restrictive and only allows access to files created by the app. This change enables users to use different scopes like `drive.readonly` for broader read access without modifying the source code.
ref: https://github.com/langchain-ai/langchain-google/issues/666
🐛 Bug Fix
- Added configurable `scopes` parameter to `GoogleDriveLoader` class
- Implemented scope validation with predefined valid scopes
- Maintained backward compatibility by using original …
> community: add scope validation for Google Drive API credentials

- libs/vertexai/langchain_google_vertexai/_anthropic_utils.py
- libs/vertexai/tests/unit_tests/test_anthropic_utils.py
update the type image input from `image_url` to `image` for compliance with the anthropic latest api
Update the type `image_url` to `image` when sending request to vertex anthropic api for compliance with the latest anthropic api format
Fixes #668
🐛 Bug Fix
> anthropic on vertexai: Update parsed parameter from `image_url` to `image`

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/langchain_google_vertexai/functions_utils.py
- libs/vertexai/poetry.lock
- libs/vertexai/pyproject.toml
- libs/vertexai/tests/integration_tests/test_anthropic_cache.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
> added google_search_tool for gemini-2

- libs/vertexai/langchain_google_vertexai/_base.py
Fix additional_headers fallback in validate_parms_base
`additional_headers` can be passed in explicitly as `None` in data dict. being processed by `validate_parms_base` and the `.get` fallback will not return the intended default value of an empty dict.
A specific usecase where this can be observed is when the VertexAI object is being created by LangChains `.configurable_fields`/ `with_config` functionality that allows to specific runtime parameters for steps in the chain.
Example:
```
llm = VertexAI(model_name="gemini-pro", project="project-ai").configurable_fields(
temperature=ConfigurableField(
id="temperature",
name="LLM Temperature",
description="The temperature of the LLM",
)
)
qa_chain = create_stuff_documents_chain(
llm.with_config(configurable={"temperature": 0.9}),
TEMPLATE, …
```
> Fix additional_headers fallback in validate_parms_base

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/unit_tests/test_chat_models.py
Tool calling with Gemini requires the tool name to be returned in the tool response, but `ToolMessage.name` is not being set when [created by a legacy agent](https://github.com/langchain-ai/langchain/blob/dbb6b7b103d9c32cea46d3848839a4c9cbb493c3/libs/langchain/langchain/agents/format_scratchpad/tools.py#L35).
Instead, `ToolMessage.additional_kwargs` is set to: `{"name": "my_tool"}`, but this isn't used when building the message Parts to send to Gemini. 
It appears this issue was caused by this change: https://github.com/langchain-ai/langchain-google/pull/671
https://github.com/langchain-ai/langchain-google/issues/711
🐛 Bug Fix
Use `ToolMessage.additional_kwargs["name"]` when `ToolMessage.name` is not present, for the tool name in the `FunctionResponse`.
> [genai] Fix tool calling with legacy agent

- libs/vertexai/langchain_google_vertexai/vectorstores/_utils.py
Fix missing `sparse_embeddings` in `vector_store.add_texts_with_embeddings()` for Vertex AI index
This PR ensures that `sparse_embeddings` are correctly stored in the Vertex AI index when using `vector_store.add_texts_with_embeddings()`. Previously, `sparse_embeddings` were not included in the index due to their absence in the `data_points_to_batch_update_records` function. This prevented hybrid search from functioning as expected.
Fixes issue #720 - sparse_embeddings are not stored in Vertex AI index when using add_texts_with_embeddings 
🐛 Bug Fix
As described in issue #720.
- Modified `data_points_to_batch_update_records` (in `libs/vertexai/langchain_google_vertexai/vectorstores/_utils.py`) to include `sparse_embeddings` in the update records.
- Added a conditional check to ensure …
> vertexai: Preserve `sparse_embeddings` in `data_points_to_batch_update_records`

- libs/genai/langchain_google_genai/_function_utils.py
- libs/genai/tests/unit_tests/test_function_utils.py
The existing code tries to handle arrays and objects in anyOf fields of JSON Schema's for tools by picking the last possible non nullable choice in anyOf. But the context of the field is not updated to reflect the selected choice leading to a borked conversion to protobuf that fails with 400 errors.
This fix is just to update the context for arrays and objects.
Please correct me if it is intentional, but there is already a testcase which is supposed to cover this, but it is buggy as it sets an `items` field within an `items` definition for an array, which should not be possible according to the JSON Schema spec. The faulty setting made this bug slip through the tests
> genai: fix function_utils to parse object/array json schemas properly

- libs/vertexai/langchain_google_vertexai/model_garden.py
- libs/vertexai/langchain_google_vertexai/utils.py
- libs/vertexai/tests/unit_tests/test_model_garden_retry.py
This PR addresses the lack of metadata displayed on LangSmith during retries in ChatAnthropicVertex. Users have reported that while error codes appear on GCP, no corresponding metadata is visible in LangSmith when retries occur. This update aims to improve observability and control over retry behavior.
https://github.com/langchain-ai/langchain-google/issues/727
🆕 New Feature
✅ Test
- Custom Retry Decorator:
Implemented a custom retry decorator using tenacity, disabling the default retry behavior in the Anthropic class for better control.
- Enhanced Logging:
Added integration with the `run_manager` (which defaults to LangchainTracer in LangSmith) to log retry events via the on_retry callback.
- Metadata Integration:
Implemented `_get_ls_params` to include additional metadata about the …
> vertexai: add retry tracing with metadata in ChatAnthropicVertex

- libs/community/langchain_google_community/bq_storage_vectorstores/bigquery.py
Added `temp_dataset_name` to the docstring for `BigQueryVectorStore`, and an explanation about how to use it to avoid needing permission to create datasets in GCP.
This attribute is defined in `BaseBigQueryVectorStore`, albeit without the additional explanation.
None.
In my environment I'm not allowed to create datasets, so was confused why `BigQueryVectorStore` asked for the `bigquery.datasets.create` permission even though the dataset already existed. Digging into the source code I found the `temp_dataset_name` attribute, and specifying it as the name of a dataset that already existed stopped this class from asking for this permission.
> docs: add temp_dataset_name to community.BigQueryVectorStore docs

- libs/community/langchain_google_community/bq_storage_vectorstores/_base.py
- libs/community/langchain_google_community/bq_storage_vectorstores/bigquery.py
In `BigQueryVectorStore`:
- Update docs for the `filter` arg to reflect the fact that it can be a dictionary or a string, and so that the IDE correctly displays them.
- Override the five similarity search methods to update their docs and type hints for the `filter` arg to reflect that fact that it can be a dictionary or a string. These overriding methods all just call the superclass methods.
In `BigQueryVectorStore` and `BaseBigQueryVectorStore` fix the indentation of the docs, so that the IDE correctly displays them.
None
🧹 Refactoring
There should be no functional changes, only to the documentation and the type hints to reflect functionality that already exists.
> docs: update docs for the filter arg in community.BigQueryVectorStore

- libs/genai/langchain_google_genai/_function_utils.py
- libs/genai/tests/unit_tests/test_function_utils.py
Fix missing required field in the tool schema when dealing with nested pydantic models. Following model 
```python
class MyModel(BaseModel):
name: str
age: int
class Models(BaseModel):
models: list[MyModel]
```
Is not populating `required` field for nested `MyModel`
```python
"function_declarations": [
{
"description": "",
"name": "Models",
...
"models": {
"description": "",
"enum": [],
"format_": "",
"items": {
"description": "MyModel",
"enum": [],
...
},
},
"required": [],   # <- Should be "required": ["name", "age"],
"type_": 6,
},
...
}
},
"required": ["models"],
"type_": 6,
},
}
]
}
```
Fixes #690, 
🐛 Bug Fix
> genai: Fix required field is ignored when dealing with nested pydantic models

- libs/vertexai/langchain_google_vertexai/model_garden.py
- libs/vertexai/tests/unit_tests/test_model_garden_timeout.py
When making requests to the Anthropic API, responses can sometimes take too long, particularly when the model is overloaded. This results in unnecessary waiting before a retry can occur. So, this PR implements timeout handling using the Anthropic SDK’s timeout parameter via http to prevent excessive wait times.
https://github.com/langchain-ai/langchain-google/issues/744
🆕 New Feature
✅ Test
- Adds a timeout parameter to the `ChatAnthropicVertex` class, allowing configurable timeout handling for API requests.
- Instantiates the corresponding Anthropic client with the specified timeout using the Anthropic SDK’s built-in timeout parameter via http.
Thank you Team!
> vertexai: add timeout in ChatAnthropicVertex

- libs/genai/tests/integration_tests/test_callbacks.py
- libs/genai/tests/integration_tests/test_chat_models.py
- libs/genai/tests/integration_tests/test_function_call.py
- libs/genai/tests/integration_tests/test_llms.py
Tests failing with
> google.api_core.exceptions.NotFound: 404 models/gemini-1.0-pro-001 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
(Unsure why but model is scheduled to be retired in 1-2 months anyway.)
> genai[patch]: update gemini 1.0 -> 1.5 and 2.0 in tests

- libs/vertexai/langchain_google_vertexai/llms.py
- libs/vertexai/tests/integration_tests/test_llms.py
Description:
Enable passing schema to ChatVertexAI client used by VertexAI object to allow it to return structured output.
> [vertexai] Add structured output to VertexAI object

- libs/community/langchain_google_community/bq_storage_vectorstores/_base.py
- libs/community/langchain_google_community/bq_storage_vectorstores/bigquery.py
Add support for specifying additional options for VECTOR_SEARCH, as described in the [docs for VECTOR_SEARCH](https://cloud.google.com/bigquery/docs/reference/standard-sql/search_functions#:~:text=options%3A%20A%20named%20argument%20with%20a%20JSON%2Dformatted%20STRING%20value.%20options_value%20is%20a%20literal%20that%20specifies%20the%20following%20vector%20search%20options%3A). The current options are `fraction_lists_to_search` and `use_brute_force`
The options are specified as a dict and converted to JSON when the query is created.
None.
🆕 New Feature
In `BigQueryVectorStore`: 
- Update `_create_search_query()` to add the options parameter to the query.
- Update `_search_embeddings()` and `batch_search()` to accept and pass the options parameter.
- Update …
> community: add support for additional VECTOR_SEARCH options

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
- libs/vertexai/tests/unit_tests/__snapshots__/test_standard.ambr
- libs/vertexai/tests/unit_tests/test_chat_models.py
Add a flag to make the call of `literal_eval` optional
Fixes #710 
🐛 Bug Fix
Hi 👋 
This is my attempt to make the usage of `literal_eval` optional. I added a flag to the ChatModel and set the default to `True` to keep it backwards compatible - however out of a security perspective I would rather suggest setting it to `False`.
In our case (we do not use `ChatPromptTemplate`), the usage of `literal_eval` is not necessary, but even leads to a bug when entering a value that is parseable as a Float ("3.14") into our chat (`TypeError: 'float' object is not iterable`)
> Bug Fix: Make call of literal_eval optional

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/unit_tests/test_chat_models.py
Current temperature validation restricts values to a maximum of 1.0. However, the Gemini API supports values up to 2.0, which allows for more creative and diverse outputs. This discrepancy led to failing code and forces to users to directly use gemini api when we need temperature value >1.
- Validation Update: Modified the temperature validation logic to accept values within the range [0.0, 2.0] instead of the previous [0.0, 1.0].
- Test Enhancement: Added a new unit test (test_temperature_range) to verify that temperature values above 1.0 up to 2.0 are accepted.
- Compatibility: Ensured that this change aligns our implementation with the Gemini API's supported range, enabling more flexible usage without breaking existing functionality.
Fixes #781
🐛 Bug Fix
- Updated temperature …
> fix[genai]: Allow Temperature Values Up to 2.0 for ChatGoogleGenerativeAI

- libs/vertexai/langchain_google_vertexai/functions_utils.py
- libs/vertexai/tests/unit_tests/test_function_utils.py
This PR enhances the `_tool_choice_to_tool_config` function within the `vertexai` package to support a new `tool_choice` format. Specifically, it adds functionality to handle tool choice dictionaries that include a `"type": "function"` key, along with a nested `"function"` object containing the `"name"` field, similar to the format used for `OpenAI` models. This change makes the configuration more flexible for handling different types of tool choices in LangChain-Google.
The PR also updates the unit test for `_tool_choice_to_tool_config` to verify that the new format is properly handled.
Fixes #697
🆕 New Feature
✅ Test
- Modified `_tool_choice_to_tool_config` to support tool added as `tool_choice={"type": "function", "function": {"name": "FuncName"}}`
- Updated unit test …
> vertexai: Support for new `tool_choice` format for Gemini models

- libs/vertexai/langchain_google_vertexai/model_garden.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
Add a `model_kwargs` field to `ChatAnthropicVertex` that can hold `thinking` params.
I tried using the Claude 3.7 thinking mode via vertex and could not find a way to enable it. I then stumbled over the comment in https://github.com/langchain-ai/langchain-google/issues/764#issuecomment-2694399270 which suggested a `model_kwargs` param which is also what the [anthropic community model](https://github.com/langchain-ai/langchain/blob/d8145dda95d5a3d7c3e9feea1ff30eef25b14f00/libs/community/langchain_community/llms/anthropic.py#L67) does.
However I am not really sure if this is the desired or approach or if I am overseeing an existing solution here - I assume that https://github.com/langchain-ai/langchain-google/pull/790 already required a solution for this?
> Add model_kwargs to ChatAnthropicVertex to enable thinking mode

- libs/genai/README.md
code example for multimodal outputs in chains is in the wrong inverted commas in readme
> readme: updated inverted commas for proper code block

- libs/vertexai/langchain_google_vertexai/chat_models.py
ChatVertexAI stores a function call in `additional_kwargs`. This is retained for backwards compatibility, but isn't structured to hold multiple tool calls. The `.tool_calls` attribute is used for this purpose, and all documentation uses it over `additional_kwargs["function_call"]`.
We currently emit a warning about this whenever parallel tool calls are generated. This leads to confusion from users, who look for ways to suppress or fix the warning even if they are working with tool calls as-intended. See for example https://github.com/langchain-ai/langgraph-supervisor-py/issues/48.
Here we remove the warning, as use of `.tool_calls` has been the documented norm for some time.
> vertexai[patch]: remove warning emitted during parallel tool calls

- libs/vertexai/langchain_google_vertexai/chat_models.py
This PR fixes an incorrect import statement in the documentation for `ChatVertexAI` in the `langchain-google-vertexai` package. The current example in `libs/vertexai/langchain_google_vertexai/chat_models.py` uses `import google.cloud.aiplatform_v1beta1.types import Tool as VertexTool`, which is syntactically incorrect and will raise a `SyntaxError`. The correct import statement is `from google.cloud.aiplatform_v1beta1.types import Tool as VertexTool`.
Fixes #814 
- Updated the import statement in the "Use Search with Gemini 2" example in `libs/vertexai/langchain_google_vertexai/chat_models.py` from `import google.cloud.aiplatform_v1beta1.types import Tool as VertexTool` to `from google.cloud.aiplatform_v1beta1.types import Tool as VertexTool`.
This is a documentation …
> [vertexai] docs: Fix incorrect import statement in `ChatVertexAI` documentation

- libs/vertexai/langchain_google_vertexai/vectorstores/vectorstores.py
Adding `credentials` as an argument to `VectorSearchVectorStore` and `VectorSearchVectorStoreDatastore`'s factory method to allow `google.oauth2` `Credentials` based authentication method.
Fixes #802.
🐛 Bug Fix
> vertexai: allow passing google.oauth2 Credentials to vectorstores

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/langchain_google_genai/llms.py
- libs/genai/tests/unit_tests/test_chat_models.py
- libs/genai/tests/unit_tests/test_llms.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/langchain_google_vertexai/llms.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
- libs/vertexai/tests/unit_tests/test_llm.py
Add warnings for invalid keyword arguments during initialization of `ChatGoogleGenerativeAI`, `ChatVertexAI`, `GoogleGenerativeAI`, and `VertexAI`. This prevents silent failures when users provide incorrect arguments (e.g `safety_setting` instead of `safety_settings`). Improves usability and debugging across both chat and LLM models in the `genai` and `vertexai` packages.
Fixes #556
🐛 Bug Fix
✅ Test
- `genai/langchain_google_genai/chat_models.py`: Added `__init__` with argument validation for `ChatGoogleGenerativeAI`.
- `genai/langchain_google_genai/llms.py`: Added `__init__` with argument validation for `GoogleGenerativeAI`.
- `vertexai/langchain_google_vertexai/chat_models.py`: Modified `__init__` in `ChatVertexAI` to include validation.
- `vertexai/langchain_google_vertexai/llms.py`: …
> [genai, vertexai]: Add warnings for invalid kwargs

- libs/vertexai/langchain_google_vertexai/_anthropic_utils.py
- libs/vertexai/langchain_google_vertexai/model_garden.py
- libs/vertexai/tests/integration_tests/test_model_garden.py
- libs/vertexai/tests/unit_tests/test_anthropic_utils.py
While streaming Claude 3.7 Thinking mode responses, langchain-core throws the following error when attempting to merge the chunks:
```
content='' additional_kwargs={} response_metadata={} id='xyz' usage_metadata={'input_tokens': 50, 'output_tokens': 0, 'total_tokens': 50}
content=[{'thinking': 'I', 'type': 'thinking', 'index': 0}] additional_kwargs={} response_metadata={} id='xyz'
content=[{'thinking': ' need to solve for x in the equation 3', 'type': 'thinking', 'index': 0}] additional_kwargs={} response_metadata={} id='xyz'
Traceback (most recent call last):
File "claude_3_vertex.py", line 75, in <module>
for chunk in llm.stream(input=[HumanMessage(content=chat_text)]):
File ".env/lib64/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 439, in stream …
```
> vertexai: Fixed content coercion while streaming Claude thinking response

- libs/genai/langchain_google_genai/chat_models.py
Fine tuned Gemini models (created by following [this tutorial](https://ai.google.dev/gemini-api/docs/model-tuning/tutorial?lang=python)) could be loaded and called via the Python Genai SDK but could not via ChatGoogleGenerativeAI before this fix, so they could not be used with Langchain. Now they can. 
Fixes #631 
🐛 Bug Fix
Test script:
```
from google import genai
from google.genai import types
from langchain_google_genai import ChatGoogleGenerativeAI
client = genai.Client()
def call_tuned_model_langchain(model, input_text):
model=client.models.get(model=model)
print(model.name)
llm = ChatGoogleGenerativeAI(model=model.name)
response = llm.invoke(input_text)
print(response.content)
call_tuned_model_langchain("tunedModels/nextnumberseries-model-cuka8h2kv06n", "seven") 
```
Error trace …
> genai: remove automatic 'models/' prefix addition for tuned type models

- libs/genai/langchain_google_genai/chat_models.py
Remove warning associated with change in behavior from https://github.com/langchain-ai/langchain-google/pull/772.
It's undesirable to emit warnings for users following intended usage patterns as it can lead to confusion.
I don't feel strongly about when we remove the warning, in case we want to keep it around for N more weeks. But I'm also OK to remove at this point.
> genai[patch]: remove warning emitted during structured output

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/langchain_google_vertexai/functions_utils.py
When using a JSON schema with references, the method `langchain_google_vertexai.chat_models.ChatVertexAI.with_structured_output` logs a warning, stating that the key `'$defs’` is not supported. This holds if the JSON schema is passed as a dictionary or a typed dict type, or if it is passed as a Pydantic model with the (default) keyword argument `method = None`. (The case of a Pydantic model with the keyword argument `method="json_mode"` is already handled.)
Fixes [#659](https://github.com/langchain-ai/langchain-google/issues/659).
🐛 Bug Fix
- The implementation of the method `langchain_google_vertexai.chat_models.ChatVertexAI.with_structured_output` is changed such that in the case `method="json_mode"`, the helper function `langchain_google_vertexai._utils.replace_defs_in_schema` is …
> vertexai: Fix resolving of references in ChatVertexAI.with_structured_output

- libs/vertexai/langchain_google_vertexai/__init__.py
📖 Documentation: fix typo in `libs/vertexai/langchain_google_vertexai/__init__.py` — corrected "foundational" spelling
N/A
- Fixed a typo in the word “foundational” under the Supported Integrations section.
N/A — typo fix only, no code changes.
No functional changes introduced.
> doc(vertexai): typo in doc

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/poetry.lock
- libs/vertexai/pyproject.toml
- libs/vertexai/tests/integration_tests/test_chat_models.py
- libs/vertexai/tests/integration_tests/test_standard.py
We're rolling out a standard format for content blocks for multi modal data (see https://github.com/langchain-ai/langchain/pull/30746).
Here we add support in ChatVertexAI. Currently just testing images + PDF.
> vertexai[patch]: support standard format for multi-modal content blocks

- libs/genai/langchain_google_genai/chat_models.py
Do not remove erroneous newline characters in streaming mode.
If I generate python code, then removing new line in the end of chunk will cause invalid code
🐛 Bug Fix
> genai: fix issue where newlines were stripped during streaming

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/unit_tests/test_chat_models.py
Makes the traced value the same as Vertex
> fix: Trace model name without `models/` prefix

- libs/genai/langchain_google_genai/_function_utils.py
- libs/genai/tests/unit_tests/test_function_utils.py
Fixes a bug in function calling schema generation where parameters with doubly nested lists (e.g., `List[List[str]]` or `List[List[Any]]`) resulted in an invalid GAPIC schema, causing a `400 Invalid argument` error from the Gemini API.
The error message typically indicated a missing field deep within the nested structure: `...properties[<param>].items.properties[<nested_param>].items.items: missing field.`
The root cause was traced to the `_get_items_from_schema` helper function. When processing the schema for an array item (`type: ARRAY`), it did not correctly handle cases where the item's schema (`items` definition) was *itself* an array. It failed to recursively apply the main formatting logic (`_format_json_schema_to_gapic`) to the nested `items` definition.
This PR modifies …
> fix(genai): Fix nested array schema conversion for function calling

- libs/community/langchain_google_community/_utils.py
- libs/community/langchain_google_community/calendar/base.py
- libs/community/langchain_google_community/calendar/toolkit.py
- libs/community/langchain_google_community/calendar/utils.py
- libs/community/langchain_google_community/gmail/base.py
- libs/community/langchain_google_community/gmail/toolkit.py
- libs/community/langchain_google_community/gmail/utils.py
There is some redundancy in creating google api resources for gmail and google calendar. To avoid duplicate code and smoother service building for future APIs, Some of the authentication is moved to the _utils file in the parent directory
Fixes #890
🧹 Refactoring
> community: Unify google service authentications and move to parent's _utils file

- libs/genai/langchain_google_genai/chat_models.py
Fix deprecation warning in langchain_google_genai due to Pydantic v2.11+
Fixes #917
🐛 Bug Fix
- Update `chat_models.py` to access `model_fields` through the class instead of the instance
- This addresses the Pydantic v2.11+ deprecation warning: "Accessing the 'model_fields' attribute on the instance is deprecated"
- Verified the warning no longer appears when using ChatGoogleGenerativeAI with structured output as Pydantic object
- Tested with Pydantic 2.11.4 and langchain-google-genai 2.1.4
- All existing tests pass with the change
This is a small fix that ensures compatibility with the upcoming Pydantic v3.0 by following the recommended pattern of accessing model fields through the class rather than instance.
> genai: fix update model_fields access for Pydantic v2.11+ compatibility

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
It is possible that a tool returns an empty list, which is a valid response. Currently, `_parse_chat_history_gemini` didn't check if the list is empty and tries to take the first element and return it as content.
🐛 Bug Fix
- check if `parsed_content` is an empty list and if so assign empty string as content
> [vertexai]: fix IndexError when a tool returns an empty list

- libs/genai/langchain_google_genai/chat_models.py
Fix AttributeError when accessing undefined 'thought' field implementing defensive attribute checking.
Fixes #956
🐛 Bug Fix
- Replace direct attribute access `part.thought` with safe attribute checking using `hasattr(part, 'thought') and part.thought`
- Prevent AttributeError when processing Part objects without 'thought' field
- Maintain backwards compatibility with existing Part objects
> [genai]: Quick fix for "Unknown field for Part: thought"

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/langchain_google_vertexai/functions_utils.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
ChatVertexAI already supports grounding / search via `bind_tools([{"google_search": {}}])`.
Here we do the same for the `code_execution` tool.
> vertexai[patch]: support code_execution

- libs/community/langchain_google_community/vertex_rank.py
- libs/community/tests/unit_tests/test_rank.py
For productive use of the rerank api, I need to be able to set a timeout to end the request after a certain time so that I can continue with my workflow.
🆕 New Feature
* Timeout has been added to unit test.
> [community]: Adding optional timeout parameter to Vertex Reranker

- libs/community/Makefile
The GitHub Actions CI workflow was failing during the testing of this pr : #805
```make: *** [Makefile:38: lint_package] Error 1```
This failure occurred because the `mkdir $(MYPY_CACHE)` command returns a non-zero exit code when the directory already exists. While this behavior is silently ignored in local development environments
but  GitHub Actions treats  it  as a failure and stops the workflow.
Added the `-p` flag to the `mkdir` command:
🐛 Bug Fix
> (community) : Fix GitHub Actions lint failure

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/integration_tests/test_chat_models.py
Following https://github.com/langchain-ai/langchain-google/pull/937
`include_thoughts` breaks immediately in a multi-turn conversation
> genai[patch]: handle thinking blocks on input

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/integration_tests/test_chat_models.py
- libs/genai/tests/integration_tests/test_standard.py
Addresses two issues:
1. `output_tokens` in [usage_metadata](https://python.langchain.com/api_reference/core/messages/langchain_core.messages.ai.UsageMetadata.html) currently does not include thought token counts. Here we add those so that `input_tokens` + `output_tokens` = `total_tokens`.
2. refactor to use utility functions for adding and subtracting usage metadata in core.
> genai[patch]: fix totals in usage metadata and refactor

- libs/genai/tests/integration_tests/test_chat_models.py
- libs/genai/tests/integration_tests/test_embeddings.py
- Image tests are very hit or miss - temporarily xfail while investigating a more reliable way to get expected output
- Mark embed test with asyncio to satisfy event loop requirement
> fix(tests): embeddings and chat_models test fixes

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
This PR adds support for handling image output in ChatVertexAI when code execution generates plots (e.g using matplotlib). The changes ensure that image data (in formats like PNG, JPEG, or GIF) is properly converted to base64-encoded URLs and included in the response similar to `langchain_google_genai`, addressing the issue where image data was not returned.
Fixes #1048 
🐛 Bug Fix
✅ Test
- Modified `libs/vertexai/langchain_google_vertexai/chat_models.py`:
- Updated `_parse_response_candidate` to handle `inline_data` with image MIME types, converting image data to base64-encoded URLs in the response content.
- Modified `libs/vertexai/tests/unit_tests/test_chat_models.py`:
- Added test cases to cover scenarios where response candidates include image data (e.g., PNG, JPEG, GIF).
- Ensured …
> vertexai: Add support for image output in ChatVertexAI code execution

- libs/vertexai/langchain_google_vertexai/_anthropic_utils.py
- libs/vertexai/langchain_google_vertexai/model_garden.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
- Add reusable _create_usage_metadata() function matching langchain_anthropic
- Fix streaming message_start events to extract cache tokens
- Fix streaming message_delta events to follow official pattern
- Unify non-streaming to use same logic for consistency
- Use proper LangChain UsageMetadata structure with input_token_details
- Remove custom CacheUsageMetadata class in favor of standard types
Fixes missing cache token information in streaming responses to match official langchain_anthropic behavior and enable proper cost tracking.
🆕 New Feature
🐛 Bug Fix
🧹 Refactoring
✅ Test
> fix: Add cache token support to ChatAnthropicVertex streaming responses

- libs/genai/tests/integration_tests/test_chat_models.py
- libs/genai/tests/integration_tests/test_standard.py
Fixed failing integration tests caused by external image URL access issues. The Wikipedia image URL used in tests returns 403 Forbidden when accessed via Python's requests library, causing test failures that were unrelated to code changes.
Changes
- `test_chat_models.py`: Updated image URL from Wikipedia to https://httpbin.org/image/jpeg
- `test_standard.py`: Added custom `test_image_inputs()` to override the hardcoded Wikipedia URL in `langchain-tests`  with the same reliable image URL
> fix(genai): Update image input tests

- libs/vertexai/langchain_google_vertexai/functions_utils.py
- libs/vertexai/tests/unit_tests/test_function_utils.py
Add proper `anyOf` handling to `_format_json_schema_to_gapic_v1` to ensure consistent formatting between Pydantic V1 and V2 Union types.
Base case is reached when a schema contains only `'type'`, `'title'`, and keys in `_ALLOWED_SCHEMA_FIELDS_SET`.
> fix(vertexai): add Union type support to V1 schema formatter

- libs/genai/langchain_google_genai/_common.py
`retries` is now an alias for `max_retries` and `request_timeout` is an alias for `timeout`.
> feat(genai): add aliases for `timeout` and `max_retries`

- libs/genai/langchain_google_genai/chat_models.py
was missing; existed in `_chat_with_retry()`
> feat(genai): copy retry logic to async `chat_with_retry`

- libs/genai/langchain_google_genai/embeddings.py
Defer async client initialization in GoogleGenerativeAIEmbeddings to first async use.\n\n- Set async_client=None in validator; lazy-create via _async_client property\n- Avoid implicit event loop creation during sync init\n- Align behavior with Chat model lazy pattern\n- Verified with unit tests (embeddings) and lint_package target locally\n\Fixes #1064
> fix(genai): defer async client init for embeddings; avoid eager loop creation

- libs/genai/README.md
- libs/genai/tests/integration_tests/test_callbacks.py
- libs/genai/tests/integration_tests/test_chat_models.py
- libs/genai/tests/integration_tests/test_function_call.py
- libs/genai/tests/integration_tests/test_llms.py
- libs/genai/tests/integration_tests/test_tools.py
- libs/genai/tests/unit_tests/test_chat_models.py
- libs/genai/tests/unit_tests/test_embeddings.py
- libs/genai/tests/unit_tests/test_llms.py
- libs/vertexai/tests/integration_tests/conftest.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
- libs/vertexai/tests/unit_tests/test_llm.py
Use the latest `gemini-flash-lite-latest` model across various tests for cost savings/efficiency.
> test: use `gemini-flash-lite-latest`
