- libs/vertexai/langchain_google_vertexai/_image_utils.py
- Also simplified Blob Retrieval code
> fix: Fixed Spelling Error in `_bytes_from_gsc()`

- libs/vertexai/langchain_google_vertexai/__init__.py
`VertexAIEmbeddings` and `GemmaChatLocalHF`
> fix: Added Missing imports into `__init__.py`

- libs/vertexai/langchain_google_vertexai/llms.py
- libs/vertexai/tests/unit_tests/test_llm.py
> fix temperature=0

- libs/vertexai/langchain_google_vertexai/chat_models.py
Related to https://github.com/langchain-ai/langchain/discussions/18975
> docs: fix with_structured_output examples

- libs/vertexai/langchain_google_vertexai/_image_utils.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
Allows remote generation for Images, Videos, Large Text files, etc.
> feat: Allow Remote loading of GCS files in Chat Messages

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/langchain_google_genai/llms.py
- libs/genai/tests/unit_tests/test_chat_models.py
Implements https://github.com/langchain-ai/langchain-google/issues/114
> Support additional headers with ChatGoogleGenerativeAI requests

- .github/workflows/_test_release.yml
Reverts langchain-ai/langchain-google#187
> Revert "Fix release dependencies"

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/integration_tests/test_chat_models.py
> fixed system instruction

- libs/genai/langchain_google_genai/embeddings.py
- libs/genai/tests/unit_tests/test_embeddings.py
> Add batch size param for embeddings

- libs/vertexai/langchain_google_vertexai/_base.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
> fixed default safety_settings

- libs/vertexai/langchain_google_vertexai/_utils.py
- libs/vertexai/tests/integration_tests/test_medlm.py
> fix and tests for MedLM

- libs/vertexai/langchain_google_vertexai/_base.py
> passing credentials as arg to the client

- libs/vertexai/langchain_google_vertexai/chat_models.py
> fixed merging streaming chunks

- libs/vertexai/langchain_google_vertexai/_base.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/langchain_google_vertexai/gemma.py
- libs/vertexai/langchain_google_vertexai/model_garden.py
part of [#22296](https://github.com/langchain-ai/langchain/issues/22296)
> docs: ChatVertexAI rich docstring

- libs/genai/langchain_google_genai/llms.py
> pass the generation_config when using stream function

- libs/community/langchain_google_community/bq_storage_vectorstores/bigquery.py
- Format the text nit.
- Add additional info for job statistics.
> docs: add more docs info for BQVectorStore

- libs/genai/langchain_google_genai/embeddings.py
> fix api_key readout for embeddings

- libs/vertexai/langchain_google_vertexai/_anthropic_utils.py
- libs/vertexai/langchain_google_vertexai/model_garden.py
Patching anthropic tool calls from the following PRs from langchain main repo
* https://github.com/langchain-ai/langchain/pull/22687
* https://github.com/langchain-ai/langchain/pull/22721
> anthropic [patch] add tool_result type to ToolMessage content

- libs/community/tests/integration_tests/test_rank.py
Modify ranking integration test due to relevance scores
> modify ranking test check

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
- Added the parameter `response_schema` to ChatVertexAI
> Add enforce json schema to ChatVertexAI

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/integration_tests/test_chat_models.py
> fix async calls without event_loop

- PULL_REQUEST_TEMPLATE.md
PR template is added like this.
docs: add PULL_REQUEST_TEMPLATE.md ...
(This can be ommited)
List the specific changes made in this PR. For example:
- Added new feature X
- Modified function Y to improve performance
- Refactored module Z for better readability
- Updated documentation for feature A
Describe the testing process:
- Test cases added/modified
- Steps to reproduce the test scenarios
- Expected vs. actual results
- Any specific testing environment or setup required
Additional information about the PR:
- Any known limitations or edge cases
- Potential impacts on other parts of the system
- Future improvements or related work planned
- Any decisions made or alternatives considered during implementation
> docs: add PULL_REQUEST_TEMPLATE.md

- libs/vertexai/langchain_google_vertexai/functions_utils.py
- libs/vertexai/tests/unit_tests/test_function_utils.py
Added support for allOf when it has only one element in the list (Pydantic converts fields like A: A = Field(...) to allOf)
#263 
🆕 New Feature
> added support for allOf

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
Deprecating the default model_name for ChatVertexAI (it's currently `chat-bison` that is an outdated model).
🧹 Refactoring
> added deprecation warning for a default model_name

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/unit_tests/test_chat_models.py
Make ChatGoogleGenerativeAI serializable
#303 
🆕 New Feature
> make ChatGoogleGenerativeAI serializable

- libs/vertexai/langchain_google_vertexai/gemma.py
- libs/vertexai/langchain_google_vertexai/model_garden_maas/_base.py
- libs/vertexai/langchain_google_vertexai/model_garden_maas/mistral.py
fix default params + added support for Gemma 2B
🐛 Bug Fix
> fix default params + added support for Gemma 2B

- libs/vertexai/langchain_google_vertexai/vectorstores/vectorstores.py
- libs/vertexai/tests/unit_tests/test_vectorstores.py
PR implements the feature described as missing in https://github.com/langchain-ai/langchain-google/issues/435. The VectorStores are now able to receive custom document ids and use them to create/update the index and upload the documents to google cloud storage. I added a unit test that checks if the custom ids are used, instead of creating unique ids.
Additionally, i updated and formatted the docstrings in the file.
https://github.com/langchain-ai/langchain-google/issues/435
🆕 New Feature
✅ Test
`_BaseVertexAIVectorStore.add_texts`
`tests/unit_tests/test_vectorstores.test_add_texts_with_custom_ids`
Ran tests using `make tests`. All passed, 12 Warnings.
The documentation on https://python.langchain.com/v0.1/docs/integrations/vectorstores/google_vertex_ai_vector_search/ …
> vertexai: added support for custom ids and sprinkled in some docstring updates

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/integration_tests/test_chat_models.py
- libs/genai/tests/integration_tests/test_embeddings.py
- libs/genai/tests/unit_tests/test_chat_models.py
- libs/genai/tests/unit_tests/test_embeddings.py
google_api_key of ChatGoogleGenerativeAI is defined as SecretStr.
This PR changes it from str in tests.
✅ Test
> genai: use SecretStr for api_key

- libs/vertexai/langchain_google_vertexai/embeddings.py
Resolves https://github.com/langchain-ai/langchain-google/issues/497
> vertexai[patch]: call model_rebuild in embeddings

- libs/vertexai/langchain_google_vertexai/chat_models.py
(I saw error in vertexai, but I cannot get the cause.)
This PR is for confirm about llm-integration-tests error.
Btw, this change may merged also(little better).
> vertexai: apply format for chat_models.py

- libs/vertexai/langchain_google_vertexai/_base.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
Add seed parameter to VertexAI generation config
N/A
🆕 New Feature
> vertexai: add seed parameter

- libs/community/langchain_google_community/bq_storage_vectorstores/_base.py
- libs/community/langchain_google_community/bq_storage_vectorstores/bigquery.py
- libs/community/tests/integration_tests/feature_store/test_feature_store_bq_vectorstore.py
- libs/community/tests/integration_tests/feature_store/test_feature_store_fs_vectorstore.py
add temp dataset parameter to BQ and FS vectorstores
Fixes #498 
🆕 New Feature
> community: add temp dataset parameter to BQ and FS vectorstores

- libs/vertexai/langchain_google_vertexai/_utils.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
Includes `avg_logprobs` in the response metadata
Fixes #525
🆕 New Feature
> vertexai: Include avg_logprobs in response metadata

- libs/vertexai/langchain_google_vertexai/model_garden_maas/_base.py
- libs/vertexai/tests/integration_tests/test_maas.py
> added support for Llama 3.2

- libs/vertexai/tests/integration_tests/test_chat_models.py
🆕 New Feature
🐛 Bug Fix
🧹 Refactoring
✅ Test
> disable test as we can't generate service account key on gcp

- libs/community/langchain_google_community/bq_storage_vectorstores/bigquery.py
Add support for `DOT_PRODUCT` distance for BigQueryVectorStore.
`DOT_PRODUCT` is supported in BQ: [doc](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_vector_index_statement)
🆕 New Feature
📖 Documentation (auto-generated)
Add `DOT_PRODUCT` in the list of supported distance types.
> community: Add support for DOT_PRODUCT distance for BigQueryVectorStore

- libs/genai/langchain_google_genai/chat_models.py
issues/561
🐛 Bug Fix
adding support for flash series of model for tools selection
tested in local by making sure that tools selection is now working for flash series of model
> Added support for tools for flash series of models in langchain-google-cenai

- libs/vertexai/langchain_google_vertexai/_utils.py
Added support for `medlm-large-1.5@001`.
GoogleModelFamily class will return GEMINI_ADVANCED for `medlm-large-1.5@001` model.
None
🆕 New Feature
Updated `GoogleModelFamily.gemini_advanced_models` to include `medlm-large-1.5@001`
> langchain-google-vertexai:Added support for medlm-large-1.5@001 in vertexai GoogleModelFamily

- libs/vertexai/langchain_google_vertexai/utils.py
- libs/vertexai/tests/integration_tests/test_chains.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
- libs/vertexai/tests/integration_tests/test_standard.py
Fixes context caching with tools, fix other flakey test
N/A
🐛 Bug Fix
✅ Test
> [vertexai]: Fix context caching with tools & flakey test

- libs/community/langchain_google_community/bq_storage_vectorstores/bigquery.py
Fixed two bugs in BQ Vector Store inside the method `batch_search`
1. When passing queries instead of embeddings, the code was generating embeddings using `embedding_model.embed_documents` which is often the modality to encode documents instead of queries. 
2. The method works by creating a temporary table in BQ with embeddings in it and then performing the search using this table as input. When the batch is large enough however, the method `_bq_client.load_table_from_dataframe(df, table)` perform the operations in batches that results in saving a temp table where the order is not preserved. The fix consists in saving an additional field `row_num` that allow us to rebuild the initial input order.
🐛 Bug Fix
> [community] Fix BQ Vector Store batch search

- libs/community/langchain_google_community/bq_storage_vectorstores/featurestore.py
Updated to allow **numeric_filters** as these are now supported by [NearestNeighborQuery](https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.types.NearestNeighborQuery). 
🆕 New Feature
🐛 Bug Fix
Added parameter definition and usage for numeric_filters.
> Update featurestore.py to allow the option of numeric filters. 

- libs/vertexai/langchain_google_vertexai/_utils.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
- Added `probability_score` and `severity_score`, which were missing from `safety_ratings`
- https://github.com/googleapis/python-aiplatform/blob/1b2457f845a2782850075fb646f04a0859a5abf7/google/cloud/aiplatform_v1/types/content.py#L591-L610
- Updated docstring
🐛 Bug Fix
- It seems the CI llm-integration-test is failed because of the quota exceeded
- `ResourceExhausted: 429 Unable to submit request because you've reached the maximum number of requests with logprobs you can make per day. Remove logprobs from the request or try again tomorrow..`
- https://github.com/langchain-ai/langchain-google/pull/656/checks?check_run_id=34639820461
> vertexai: add probability_score and severity_score to safety_ratings

- libs/vertexai/langchain_google_vertexai/functions_utils.py
Remove redundant debug messages
🐛 Bug Fix
> fix: Remove redundant debug messages

- libs/vertexai/langchain_google_vertexai/_base.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
- libs/vertexai/tests/integration_tests/test_llms.py
- libs/vertexai/tests/integration_tests/test_vectorstores.py
> fixed default transport for async client

- libs/vertexai/langchain_google_vertexai/chat_models.py
"remoced" should be spelled "removed"
> vertexai: fix typo in error message

- libs/genai/langchain_google_genai/chat_models.py
It  filters out the messages with content parameter being empty  in the `_prepare_request` method.
Fixes : #691
🐛 Bug Fix
> genai : filter out empty message contents in ChatGoogleGenerativeAI

- libs/genai/README.md
- libs/genai/langchain_google_genai/__init__.py
- libs/genai/langchain_google_genai/_common.py
- libs/genai/langchain_google_genai/_enums.py
- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/integration_tests/test_chat_models.py
- libs/genai/tests/unit_tests/test_imports.py
Added field response_modalities to ChatGoogleGenerativeAI initialization, this is to allow multimodal output when the ChatGoogleGenerativeAI is used in langchain chains
🆕 New Feature
✅ Test
Here I propose to set the Field with type with Modality rather than Strings, while the later could work but probably more error prone, please let me know WDYT.
> genai: Added field response_modalities in ChatGoogleGenerativeAI initialization.

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/integration_tests/test_chat_models.py
Fixes : #730
This PR adds support for the code execution feature available in Gemini models (1.5 Pro, 1.5 Flash, 2.0 Flash, and 2.0 Pro).
1. Is this the right approach for implementing code execution support?
2. For parsing responses with code execution results, I'm planning to modify `_parse_response_candidate` to handle:
- `executable_code` parts
- `code_execution_result` parts
- Inline data (images/charts)
Is there a preferred way to structure this in LangChain's message format?
`Current Output from Local Testing:
Here’s how the implementation behaves when executed locally:`
🆕 New Feature
> (genai): Add support for Gemini code execution

- libs/vertexai/langchain_google_vertexai/_anthropic_utils.py
- libs/vertexai/langchain_google_vertexai/model_garden.py
- libs/vertexai/tests/unit_tests/test_anthropic_utils.py
Add GCS `gs://` image support in ChatAnthropicVertex model
Fixes #794 
🆕 New Feature
🧹 Refactoring
Adding @lkuligin for a review.
> Add GCS image support in ChatAnthropicVertex model

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
- libs/vertexai/tests/integration_tests/test_evaluation.py
https://github.com/langchain-ai/langchain-google/issues/748
> vertexai[patch]: return model name in response metadata when streaming

- libs/vertexai/poetry.lock
- libs/vertexai/pyproject.toml
> vertexai: release 2.0.18

- libs/genai/langchain_google_genai/chat_models.py
Added a transport check for GenAI like in VertexAI. Now if an async method like `ainvoke()` is called, the async client is created with a transport field automatically set to "grpc_asyncio" if "rest" was passed originally. 
The equivalent VertexAI implementation that this PR replicates for GenAI: https://github.com/langchain-ai/langchain-google/blob/480a8b277b08e9060537b0435fe7bebcc7dc413a/libs/vertexai/langchain_google_vertexai/_base.py#L171 
For #791 
🐛 Bug Fix
> genai: added transport check for async client in ChatGoogleGenerativeAI class

- libs/genai/langchain_google_genai/chat_models.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
Added documentation for the context caching feature in `ChatGoogleGenerativeAI` and `ChatVertexAI`. For `genai`, included examples for caching a single file directly and multiple files using `Part`. For `vertexai`, provided a consolidated example caching content from GCS using `Part`. Examples were borrowed from official google documentations [vertexai](https://cloud.google.com/vertex-ai/generative-ai/docs/context-cache/context-cache-create) [genai](https://ai.google.dev/gemini-api/docs/caching?lang=python). These updates enhance user guidance on leveraging context caching with LangChain.
Fixes #746 
- Updated `langchain-google/libs/genai/langchain_google_genai/chat_models.py`:
- Added "Context Caching" section with "Single File Example" and "Multiple Files Example".
- …
> [genai, vertexai]: add context caching examples for genai and vertexai in doc

- libs/vertexai/langchain_google_vertexai/vectorstores/vectorstores.py
Refactored the `embeddings` property handling in `VectorStore` to ensure proper overriding from parent class. The previous implementation had a typo(`embbedings`) or mismatch that caused the property to not be overridden correctly, leading to unexpected behavior when accessing `embeddings`.  
🐛 Bug Fix
🧹 Refactoring
Ensured that the `embeddings` property is correctly overridden and accessed via `@property`.
> vertexai: fix embedding property override issue in VectorStore

- libs/vertexai/tests/integration_tests/test_chat_models.py
`str | None` -> `Optional[str]`
> vertexai[patch]: fix python 3.9 compatibility in test

- libs/vertexai/langchain_google_vertexai/vectorstores/vectorstores.py
Fix a issue where Document IDs were being saved as `null` when using `add_texts_with_embeddings`. 
```json
{"id": null, "metadata": {}, "page_content": "m", "type": "Document"}
```
This change ensures that the correct `id` is preserved and stored properly.
🐛 Bug Fix
> vertexai: fix null ids in `add_texts_with_embeddings`

- libs/vertexai/langchain_google_vertexai/_base.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
Added audio_timestamp support.
Fixes #868 
🆕 New Feature
✅ Test
> vertexai: Added audio_timestamp support.

- libs/vertexai/README.md
Added a comprehensive README for the `langchain-google-vertexai` package including installation instructions, detailed usage examples for chat models, embeddings, multimodal inputs, and code generation capabilities. Also added a content list for easy navigation.
None
* Added detailed usage sections for chat models and embeddings
* Included examples for multimodal inputs and outputs
* Added code generation usage examples
* Added a content list at the top for better README navigation
Manual verification of code snippets for correctness. No functional code changes.
This PR improves the developer experience by providing clear documentation for easier adoption and usage of the `langchain-google-vertexai` package.
> vertexai: docs added comprehensive README for langchain-google-vertexai integration package

- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/integration_tests/test_chat_models.py
- libs/genai/tests/integration_tests/test_llms.py
- libs/genai/tests/integration_tests/test_standard.py
`gemini-1.5-(flash/pro)-001` is being retired.
> genai[patch]: use 1.5-latest in tests

- libs/genai/langchain_google_genai/_common.py
- libs/genai/langchain_google_genai/chat_models.py
- libs/genai/tests/integration_tests/test_chat_models.py
genai: Added include_thoughts support.
🆕 New Feature
✅ Test
> genai: Added include_thoughts support.

- libs/vertexai/langchain_google_vertexai/model_garden.py
This PR adds the flexibility for `langchain-google-vertexai` to forward the `api_endpoint`/`base_url` parameter to `AnthropicVertex`. Currently, the api_endpoint is only used for VertexAI initialization. Forwarding to `AnthropicVertex` is particularly useful when specifying custom endpoints or leveraging new Vertex AI features.
For example, the following will forward the endpoint to AnthropicVertex as well:
```python
llm = ChatAnthropicVertex(
project=project_name,
credentials=credentials,
model_name=model_name,
location="global",
api_endpoint="https://aiplatform.googleapis.com/v1",
max_retries=1,
)
```
🆕 New Feature
> vertexai: Pass base_url to AnthropicVertex

- libs/vertexai/langchain_google_vertexai/functions_utils.py
- libs/vertexai/tests/unit_tests/test_function_utils.py
Fix issue #845 
1. add another edge case in unit test to surface the issue where pydantic v2 checker ends early
2. fix _format_dict_to_function_declaration function by allowing deeper recursion
#845 (updated test to catch more edge cases)
might be related: #953 structured output issue
🐛 Bug Fix
✅ Test
> [vertexai]: Fix #845 tool binding issue with anyOf Field in pydantic v2

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
When a message is a float (like "12345.0") it gets parsed and then parsing fails. Ref the new test.
None
🐛 Bug Fix
> vertexai: fixes floats parsed and assumed iterable

- libs/vertexai/README.md
- libs/vertexai/langchain_google_vertexai/__init__.py
- libs/vertexai/langchain_google_vertexai/_base.py
- libs/vertexai/langchain_google_vertexai/_enums.py
- libs/vertexai/langchain_google_vertexai/_utils.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/langchain_google_vertexai/model_garden_maas/_base.py
- libs/vertexai/tests/integration_tests/conftest.py
- libs/vertexai/tests/integration_tests/test_chat_models.py
- libs/vertexai/tests/integration_tests/test_maas.py
- libs/vertexai/tests/unit_tests/test_imports.py
Added Image Generation Support
🆕 New Feature
🧹 Refactoring
✅ Test
> vertexai: Added Image Generation Support

- libs/vertexai/langchain_google_vertexai/_anthropic_utils.py
- libs/vertexai/tests/unit_tests/test_anthropic_utils.py
Support BlockType Image for ChatAnthropicVertex.
https://github.com/langchain-ai/langchain-google/issues/1019
🐛 Bug Fix
> vertexai: fix(ChatAnthropicVertex): support BlockType Image

- libs/genai/langchain_google_genai/chat_models.py
- libs/vertexai/langchain_google_vertexai/chat_models.py
When making streaming calls to gemini using ChatVertexAI or ChatGoogleGenerativeAI, the chunk parameter was missing on the on_llm_new_token callback which was fetching metadata not possible
Added chunk as keyword parameter to both astream and stream_gemini call to on_llm_new_token methods for both ChatVertexAI and ChatGoogleGenerativeAI
🐛 Bug Fix
> vertexai/genai: Added missing chunk to on_llm_new_token to _stream_gemini

- libs/genai/langchain_google_genai/chat_models.py
Updated the documentation for `ChatGoogleGenerativeAI` in `langchain_google_genai` to include comprehensive examples for handling multimodal inputs, including PDF, video (with YouTube URL support), audio, and URI-based file uploads. The changes enhance clarity and usability by providing detailed code snippets and expected outputs for each input type. No new functionality or dependencies were added, as these features already exist in the package.
Fixes #999 #1014 
- Added examples for processing PDF, video, and audio inputs using base64 encoding in `libs/genai/langchain_google_genai/chat_models.py`.
- Included support for YouTube URL-based video input with a clear example.
- Documented URI-based file uploads using Google's file upload API.
- Provided expected output for …
> [genai] docs: enhance multimodal input examples for ChatGoogleGenerativeAI

- libs/vertexai/langchain_google_vertexai/chat_models.py
- libs/vertexai/tests/unit_tests/test_chat_models.py
Resolves https://github.com/langchain-ai/langchain-google/issues/1057.
> vertexai(patch): fix function calling for v1 endpoints

- libs/vertexai/langchain_google_vertexai/vision_models.py
> fix(vertex): use imagen-3.0-generate-002 as default model for image generation

- README.md
Updated the README to streamline contribution guidelines and improve clarity on package structure and testing.
🆕 New Feature
🐛 Bug Fix
🧹 Refactoring
✅ Test
> chore: revise `README.md`

- libs/genai/langchain_google_genai/chat_models.py
Remove direct import of `google.api_core` and replace it with specific exception.
> refactor(genai): remove direct import of `google.api_core` and use specific exceptions

- libs/genai/tests/integration_tests/test_callbacks.py
- libs/genai/tests/integration_tests/test_function_call.py
- libs/genai/tests/integration_tests/test_llms.py
- libs/genai/tests/integration_tests/test_standard.py
- libs/genai/tests/integration_tests/test_tools.py
- libs/genai/tests/unit_tests/__snapshots__/test_standard.ambr
- libs/genai/tests/unit_tests/test_chat_models.py
- libs/genai/tests/unit_tests/test_llms.py
- libs/genai/tests/unit_tests/test_standard.py
Use modern names as some previous ones are deprecated. Also parameterize some tests
> chore(genai): update model names in tests

- libs/vertexai/langchain_google_vertexai/vectorstores/_searcher.py
- libs/vertexai/langchain_google_vertexai/vectorstores/vectorstores.py
fixes #1197 
🆕 New Feature
🐛 Bug Fix
🧹 Refactoring
✅ Test
> feat(vertex): add additional args for vertex ai vector search

- libs/genai/tests/integration_tests/test_chat_models.py
- libs/genai/tests/unit_tests/test_chat_models.py
Lots of unnecessary logic that should be unit tested instead. Also de-duped many tests by parametrizing.
> refactor(genai): `test_chat_models.py`

- libs/genai/langchain_google_genai/_common.py
The current documentation incorrectly states that the default value of the `max_output_tokens` parameter is `64`.
In reality, the default varies depending on the model.
This update clarifies that the default is model-specific and adds a reference to the official Gemini API documentation for model-specific limits.
🐛 Bug Fix
> fix(genai): Fix outdated doc for max_output_tokens default value
